INSERT INTO Kota (nama) VALUES ('Ambon');
INSERT INTO Kota (nama) VALUES ('Balikpapan');
INSERT INTO Kota (nama) VALUES ('Banda Aceh');
INSERT INTO Kota (nama) VALUES ('Bandar Lampung');
INSERT INTO Kota (nama) VALUES ('Bandung');
INSERT INTO Kota (nama) VALUES ('Banjar');
INSERT INTO Kota (nama) VALUES ('Banjarbaru');
INSERT INTO Kota (nama) VALUES ('Banjarmasin');
INSERT INTO Kota (nama) VALUES ('Batam');
INSERT INTO Kota (nama) VALUES ('Batu');
INSERT INTO Kota (nama) VALUES ('Bau-Bau');
INSERT INTO Kota (nama) VALUES ('Bekasi');
INSERT INTO Kota (nama) VALUES ('Bengkulu');
INSERT INTO Kota (nama) VALUES ('Binjai');
INSERT INTO Kota (nama) VALUES ('Bitung');
INSERT INTO Kota (nama) VALUES ('Blitar');
INSERT INTO Kota (nama) VALUES ('Bogor');
INSERT INTO Kota (nama) VALUES ('Bontang');
INSERT INTO Kota (nama) VALUES ('Bukittinggi');
INSERT INTO Kota (nama) VALUES ('Cilegon');
INSERT INTO Kota (nama) VALUES ('Cimahi');
INSERT INTO Kota (nama) VALUES ('Cirebon');
INSERT INTO Kota (nama) VALUES ('Denpasar');
INSERT INTO Kota (nama) VALUES ('Depok');
INSERT INTO Kota (nama) VALUES ('Dumai');
INSERT INTO Kota (nama) VALUES ('Gorontalo');
INSERT INTO Kota (nama) VALUES ('Gunungsitoli');
INSERT INTO Kota (nama) VALUES ('Jambi');
INSERT INTO Kota (nama) VALUES ('Jayapura');
INSERT INTO Kota (nama) VALUES ('Kediri');
INSERT INTO Kota (nama) VALUES ('Kendari');
INSERT INTO Kota (nama) VALUES ('Kotamobagu');
INSERT INTO Kota (nama) VALUES ('Kupang');
INSERT INTO Kota (nama) VALUES ('Langsa');
INSERT INTO Kota (nama) VALUES ('Lhokseumawe');
INSERT INTO Kota (nama) VALUES ('Lubuklinggau');
INSERT INTO Kota (nama) VALUES ('Madiun');
INSERT INTO Kota (nama) VALUES ('Magelang');
INSERT INTO Kota (nama) VALUES ('Makassar');
INSERT INTO Kota (nama) VALUES ('Malang');
INSERT INTO Kota (nama) VALUES ('Manado');
INSERT INTO Kota (nama) VALUES ('Mataram');
INSERT INTO Kota (nama) VALUES ('Medan');
INSERT INTO Kota (nama) VALUES ('Mojokerto');
INSERT INTO Kota (nama) VALUES ('Padang');
INSERT INTO Kota (nama) VALUES ('Padang Panjang');
INSERT INTO Kota (nama) VALUES ('Padang Sidempuan');
INSERT INTO Kota (nama) VALUES ('Pagar Alam');
INSERT INTO Kota (nama) VALUES ('Palangka Raya');
INSERT INTO Kota (nama) VALUES ('Palembang');
INSERT INTO Kota (nama) VALUES ('Palopo');
INSERT INTO Kota (nama) VALUES ('Palu');
INSERT INTO Kota (nama) VALUES ('Pangkal Pinang');
INSERT INTO Kota (nama) VALUES ('Parepare');
INSERT INTO Kota (nama) VALUES ('Pariaman');
INSERT INTO Kota (nama) VALUES ('Pasuruan');
INSERT INTO Kota (nama) VALUES ('Payakumbuh');
INSERT INTO Kota (nama) VALUES ('Pekalongan');
INSERT INTO Kota (nama) VALUES ('Pekanbaru');
INSERT INTO Kota (nama) VALUES ('Pematangsiantar');
INSERT INTO Kota (nama) VALUES ('Pontianak');
INSERT INTO Kota (nama) VALUES ('Prabumulih');
INSERT INTO Kota (nama) VALUES ('Probolinggo');
INSERT INTO Kota (nama) VALUES ('Sabang');
INSERT INTO Kota (nama) VALUES ('Salatiga');
INSERT INTO Kota (nama) VALUES ('Samarinda');
INSERT INTO Kota (nama) VALUES ('Sawahlunto');
INSERT INTO Kota (nama) VALUES ('Semarang');
INSERT INTO Kota (nama) VALUES ('Serang');
INSERT INTO Kota (nama) VALUES ('Sibolga');
INSERT INTO Kota (nama) VALUES ('Singkawang');
INSERT INTO Kota (nama) VALUES ('Solok');
INSERT INTO Kota (nama) VALUES ('Sorong');
INSERT INTO Kota (nama) VALUES ('Subulussalam');
INSERT INTO Kota (nama) VALUES ('Sukabumi');
INSERT INTO Kota (nama) VALUES ('Sungaipenuh');
INSERT INTO Kota (nama) VALUES ('Surabaya');
INSERT INTO Kota (nama) VALUES ('Surakarta');
INSERT INTO Kota (nama) VALUES ('Tangerang');
INSERT INTO Kota (nama) VALUES ('Tangerang Selatan');
INSERT INTO Kota (nama) VALUES ('Tanjungbalai');
INSERT INTO Kota (nama) VALUES ('Tanjungpinang');
INSERT INTO Kota (nama) VALUES ('Tarakan');
INSERT INTO Kota (nama) VALUES ('Tasikmalaya');
INSERT INTO Kota (nama) VALUES ('Tebing Tinggi');
INSERT INTO Kota (nama) VALUES ('Tegal');
INSERT INTO Kota (nama) VALUES ('Ternate');
INSERT INTO Kota (nama) VALUES ('Tidore Kepulauan');
INSERT INTO Kota (nama) VALUES ('Tomohon');
INSERT INTO Kota (nama) VALUES ('Tual');
INSERT INTO Kota (nama) VALUES ('Yogyakarta');
INSERT INTO Kota (nama) VALUES ('Jakarta Pusat');
INSERT INTO Kota (nama) VALUES ('Jakarta Utara');
INSERT INTO Kota (nama) VALUES ('Jakarta Barat');
INSERT INTO Kota (nama) VALUES ('Jakarta Selatan');
INSERT INTO Kota (nama) VALUES ('Jakarta Timur');